deps: Add autofix capability to Dependabot PRs
Signed-off-by: Austin Ziegler <austin@zieglers.ca>

diff --git a/.github/workflows/check-dist.yml b/.github/workflows/check-dist.yml
--- a/.github/workflows/check-dist.yml
+++ b/.github/workflows/check-dist.yml
@@ -1,12 +1,10 @@
-# In TypeScript actions, `dist/` is a special directory. When you reference
-# an action with the `uses:` property, `dist/index.js` is the code that will be
-# run. For this project, the `dist/index.js` file is transpiled from other
-# source files. This workflow ensures the `dist/` directory contains the
-# expected transpiled code.
+# In GitHub Actions written in TypeScript, `dist/` is a special directory. When you
+# reference an action with the `uses:` property, `dist/index.js` is the code that will be
+# run, and `dist/index.js` file is transpiled from other source files. This workflow
+# ensures the `dist/` directory contains the expected transpiled code.
 #
-# If this workflow is run from a feature branch, it will act as an additional CI
-# check and fail if the checked-in `dist/` directory does not match what is
-# expected from the build.
+# If this workflow is run from a feature branch, it will act as an additional CI check and
+# fail if the checked-in `dist/` directory does not match what is expected from the build.
 name: Check Transpiled JavaScript
 
 on:
@@ -14,6 +12,10 @@ on:
     branches: [main]
   pull_request:
   workflow_dispatch:
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+  cancel-in-progress: true
 
 permissions: {}
 
@@ -27,7 +29,7 @@ jobs:
 
     steps:
       - name: Harden the runner
-        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
+        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
         with:
           disable-sudo: true
           egress-policy: block
@@ -70,3 +72,67 @@ jobs:
         with:
           name: dist
           path: dist/
+
+  rebuild-dist:
+    name: Rebuild dist/ for Dependabot PRs
+    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.event_name == 'pull_request'
+    runs-on: ubuntu-latest
+
+    permissions:
+      contents: write # Rewrite `dist/` and `biome.json` if required, but only for dependabot PRs.
+
+    steps:
+      - name: Harden the runner
+        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
+        with:
+          disable-sudo: true
+          egress-policy: block
+          allowed-endpoints: >
+            github.com:443
+            registry.npmjs.org:443
+            release-assets.githubusercontent.com:443
+            nodejs.org:443
+
+      - id: generate-token
+        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
+        with:
+          app-id: ${{ secrets.KINETICCAFE_BOT_CLIENT_ID }}
+          private-key: ${{ secrets.KINETICCAFE_BOT_PRIVATE_KEY }}
+
+      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
+        with:
+          ref: ${{ github.head_ref }}
+          fetch-depth: 0
+          persist-credentials: true
+          token: ${{ steps.generate-token.outputs.token }}
+
+      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 #v4.2.0
+
+      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 #v6.0.0
+        with:
+          node-version: 24.x
+          cache: pnpm
+
+      - run: pnpm install --frozen-lockfile
+
+      - name: Migrate Biome configuration
+        run: pnpm exec biome migrate --write
+
+      - name: Rebuild dist/
+        run: pnpm run all
+
+      - name: Commit and push changed dist/ and biome.json files
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git add dist/ biome.json
+
+          if ! git diff --quiet; then
+            echo "::error::There are additional changes that need review."
+            exit 1
+          elif ! git diff --staged --quiet; then
+            git commit -m "deps: Update dist/ after dependabot update"
+            git push
+          else
+            exit 0
+          fi
